FROM repo.volcanoyt.com/base:novnc-ubuntu

ENV WORK_DIR=/opt/seiscomp3 \
    BUILD_DIR=/tmp/seiscomp3 \
    REPO_PATH=https://github.com/SeisComP
ENV INSTALL_DIR $WORK_DIR
ENV PATH $PATH:$INSTALL_DIR/bin:$INSTALL_DIR/sbin
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$INSTALL_DIR/lib
ENV PYTHONPATH $PYTHONPATH:$INSTALL_DIR/lib/python

# Start clone
RUN addgroup sysop && adduser sysop --ingroup sysop --shell /bin/sh --disabled-password && \
    apt-get update && apt-get install -y --no-install-recommends git software-properties-common apt-utils && add-apt-repository ppa:rock-core/qt4 && apt-get update &&\
    mkdir $WORK_DIR && cd $WORK_DIR &&\
    git clone $REPO_PATH/seiscomp.git $WORK_DIR &&\
    cd $WORK_DIR/src/base &&\
    git clone $REPO_PATH/seedlink.git &&\
    git clone $REPO_PATH/common.git &&\
    git clone $REPO_PATH/main.git &&\
    git clone $REPO_PATH/extras.git &&\
    git clone $REPO_PATH/contrib-gns.git &&\
    git clone $REPO_PATH/contrib-ipgp.git &&\
    git clone $REPO_PATH/contrib-sed.git &&\
    mkdir -p $BUILD_DIR/build \
    && cp -r $WORK_DIR/* $BUILD_DIR/

# SeisComp dependencies
RUN apt-get install -y --no-install-recommends \
    python3 python3-pip libpython3.8 python3-numpy python3-twisted python3-dateutil \
    libqt5gui5 libqt5svg5 libqt5xml5 libqt5printsupport5 \
    libxml2 libpq5 \
    mariadb-server mariadb-client

# Build dependencies Dev Mode
RUN apt-get install -y --no-install-recommends \
    flex libssl-dev wget build-essential ca-certificates cmake cmake-curses-gui gfortran \
    # datebase
    libmysqlclient-dev libpq-dev libsqlite3-dev \
    # gui qt4
    libqt4-dev \
    # gui qt5
    qtbase5-dev libqt5svg5-dev \
    # boost
    libboost1.67-all-dev \
    # python
    python3-dev \
    # idk what this?
    libxml2-dev libfl-dev &&\
    # for re-check submodul
    pip3 install mu-repo

RUN set -ex \
    cd $BUILD_DIR/build \
    && cmake \
        -DSC_GLOBAL_GUI=ON \
        -DSC_TRUNK_DB_MYSQL=ON \
        -DSC_TRUNK_DB_POSTGRESQL=ON \
        -DSC_TRUNK_DB_SQLITE3=ON \
        -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
        .. \
    && make \
    && make install